=== adrienrouquet/cpe-tpxml/validation-xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="document">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="groups" />
				<xsd:element ref="pictures" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="groups">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="group" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="name" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>	
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
		
	<xsd:element name="group">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="groupdescription" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="groupdescription">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="name" type="xsd:string"/>
				<xsd:element ref="othernames" minOccurs="0" maxOccurs="1" />
				<xsd:element ref="childrengroup" minOccurs="0" maxOccurs="1" />
				<xsd:element name="description" type="xsd:string" />
				<xsd:element ref="pictures" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="othernames">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="othername" type="xsd:string" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="childrengroup">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="group" minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="pictures">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="picture" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:attribute name="id" type="xsd:string" use="required"/>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="picture">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="picturedescription" minOccurs="0" maxOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" use="required" />
			<xsd:attribute name="src" type="xsd:string" use="required" />
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="picturedescription">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="scientificname" type="xsd:string" />
				<xsd:element name="location" type="xsd:string" />
				<xsd:element name="sex" type="xsd:string" />
				<xsd:element name="specimencondition" type="xsd:string" />
				<xsd:element name="lifecyclestage" type="xsd:string" />
				<xsd:element name="source" type="xsd:string" />
				<xsd:element name="sourcecollection" type="xsd:string" />
				<xsd:element name="imageuse" type="xsd:string" />
				<xsd:element name="copyright" type="xsd:string" />
				<xsd:element name="copyrightyears" type="xsd:string" />
				<xsd:element name="comment" type="xsd:string" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
</xsd:schema>

=== adrienrouquet/cpe-tpxml/data-xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<document xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation='./validation-xml.xsd'>
	<groups>
		<group name="mammalia">
			<groupdescription>
				<name>
					Mammalia
				</name>
				<othernames>
					<othername>Mammals</othername>
				</othernames>
				<childrengroup>
					<group name="triconodonts"></group>
					<group name="monotremata"></group>
					<group name="multituberculata"></group>
					<group name="marsupiala"></group>
					<group name="palaeoryctoids"></group>
					<group name="eutheria"></group>
				</childrengroup>
				<description>
					Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
				</description>
				<pictures>
					<picture id="mam1" />
					<picture id="mam2" />
					<picture id="mam3" />
				</pictures>
			</groupdescription>
		</group>
		
		<group name="marsupiala">
			<groupdescription>			
				<name>
					Marsupiala
				</name>
				<othernames>
					<othername>Mammals</othername>
				</othernames>
				<childrengroup>
					<group name="didelphimorphia"></group>
					<group name="paucituberculata"></group>
					<group name="microbiotheria"></group>
					<group name="dasyuromorphia"></group>
					<group name="peramelemorphia"></group>
					<group name="notoryctemorphia"></group>
					<group name="diprotodontia"></group>
				</childrengroup>
				<description>
					Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
				</description>
				<pictures>
					<picture id="mar1" />
					<picture id="mar2" />
					<picture id="mar3" />
				</pictures>
			</groupdescription>
		</group>
	</groups>
	
	<pictures>
		<picture id="mam1">
			<picturedescription src="/img/mammalia1.jpg">
				<scientificname>Macropus giganteus</scientificname>
				<location>Goorooyarro o Nature Reserve, ACT, Australia</location>
				<sex></sex>
				<specimencondition>Live Specimen</specimencondition>
				<lifecyclestage>juvenile and adult</lifecyclestage>
				<source>Eastern Grey Kangaro</source>
				<sourcecollection>Flickr</sourcecollection>
				<imageuse>CC</imageuse>
				<copyright>David Cook</copyright>
				<copyrightyears>2008</copyrightyears>
				<comment></comment>
			</picturedescription>
		</picture>
		<!--
		<picture id="mam2" src="/img/mammalia2.jpg"></picture>
		<picture id="mam3" src="/img/mammalia3.jpg"></picture>
		<picture id="mar1" src="/img/marsupiala1.jpg"></picture>
		<picture id="mar2" src="/img/marsupiala2.jpg"></picture>
		<picture id="mar3" src="/img/marsupiala3.jpg"></picture>
		-->
	</pictures>
</document>
